Iter5
romanp1989/go-shortener pull request #5
Opened 2024-07-08 20:40 UTC by romanp1989

2024-07-15 19:50 UTC, vokinneberg requested changes
Поздравляю с завершением Первого Спринта и первым ревью! 🤗 Твой покрыт тестами, работает и проходит тесты. Отличная работа! 🚀

**Сильные стороны твоего PR:**

1. **Функциональность:** Код функционален и корректен! 🚀
2. **Тестирование:** Реализованы тесты базовых сценариев. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. **Структура сервиса:** По условию задания структура сервиса должна представлять собой набор пакетов и структур, разделённыхна слои. В твоем коде немного  этого не хватает, предлагаю подумать о том как можно было бы разделить код на слои более эффективно так чтобы было в дальнейшем удобно развивать сервис.
2. **Использование интерфейсов:** Подумай о том, как можно было бы использовать интерфейсы после того, как ты разделишь код на слои.
3. **Синхронизация доступа** к хранилищу. На будущее -стоит подумать, как будет себя вести код при конкурентной обработкенескольких запросов на сервере и как можно синхронизировать доступ кхранилищу.
4. **Обработка ошибок:** Не стоит злоупотреблять вызовом `panic` так как она приводит к крашу приложения. Рекомендую вызвать `log.Fatalf(...)`, которая выведет сообщение об ошибке и завершит процесс при помощи вызова `os.Exit(1)`.
5. **Комментарии:** Было бы здорово, если бы ты добавил комментарии в коде там, где есть сложные места, которые требуют пояснения, а также для публичных методов.
6. **Тестирование**: Стоит добавить информативные сообщения о том, что пошло не так и что ожидалось в тестах.

2024-07-15 19:50 UTC, vokinneberg commented on cmd/client/main.go
> +func main() {
По коду клиента я бы рекомендовал разделить его на несколько логических блоков, которые можно отделить пробелами — довольно сложно воспринимать непрерывную "простыню" кода.

Также я бы не рекомендовал злоупотреблять "очевидными" комментариями. В общем случае, комментарии используются либо для разделения блоков кода, либо для пояснения неочевидных мест. При разделении блоков кода, если возникает желание добавить комментарий, стоит задуматься о переносе блока в отдельную функцию с информативным именем.

2024-07-15 19:50 UTC, vokinneberg commented on cmd/client/main.go
> +		panic(err)
Не стоит использовать панику, так как она приводит к крашу приложения. Рекомендую вызвать `log.Fatalf(...)`, которая выведет сообщение об ошибке и завершит процесс при помощи вызова `os.Exit(1)`.

2024-07-15 19:50 UTC, vokinneberg commented on cmd/shortener/main.go
> +		panic(err)
Не стоит использовать панику, так как она приводит к крашу приложения. Рекомендую вызвать `log.Fatalf(...)`, которая выведет сообщение об ошибке и завершит процесс при помощи вызова `os.Exit(1)`.

2024-07-15 19:50 UTC, vokinneberg commented on cmd/client/main.go
> +	endpoint := "http://localhost:8080/"
Можно вынести endpoint и content-type за пределы метода main и объявить, как константы.

2024-07-15 19:50 UTC, vokinneberg commented on internal/handlers/handlers.go
> +	if r.Method != http.MethodPost {
Кажется эта проверка лишняя, так как `chi` автоматически выполнит эту проверку и вернет соответствующий код.

2024-07-15 19:50 UTC, vokinneberg commented on internal/config/config.go
> +		log.Fatal(err)
Не стоит использовать в этом месте  `log.Fatal(err)`, хотя это корректно завершит приложение стоит вернуть ошибку вызывающему коду и принять решение о том, как ее обработать там, тем более, что можно использовать значения по-умолчанию.

Можно реализовать метод `ParseFlags()` так чтобы он возвращал инстанс структуры конфигурации при создании приложения.

2024-07-15 19:50 UTC, vokinneberg commented on internal/handlers/handlers.go
> +	}
Не стоит забывать закрывать тело ответа после чтения.
```suggestion
	body, err := io.ReadAll(r.Body)
	if err != nil || string(body) == "" {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	defer r.Body.Close()
```

2024-07-15 19:50 UTC, vokinneberg commented on internal/handlers/handlers.go
> +	sum := md5.Sum([]byte(url))
Стоит ли как-то бороться с коллизиями хеширования?

2024-07-15 19:50 UTC, vokinneberg commented on internal/handlers/handlers.go
> +	http.Error(w, "Не найден url для указанного ID", http.StatusBadRequest)
Мне кажется более логичным, в случае если URL не найден возвращать `404 NotFound`.

2024-07-15 19:50 UTC, vokinneberg commented on internal/handlers/handlers_test.go
> +			name:        "Valid URL",
Небольшая рекомендация по именованию тестов - Go автоматически заменяет пробелы на подчерки в названиях тестов. Поэтому я бы не рекомендовал использовать пробелы в названиях или сразу заменять из на подчерки - это позволит избежать проблем про поиске упавших тестов.

2024-07-15 19:50 UTC, vokinneberg commented on internal/handlers/handlers_test.go
> +			assert.Equal(t, tt.want.responseURL, string(resBody))
В общем-то в использовании сторонних assert  библиотек нет ничего неправильного, но разработчики Go не рекоменду использовать сторонние assert библиотеки, так как _это либо останавливает тест раньше времени (если вызовы используют t.Fatalf или panic), либо упускает интересную информацию о том, что тест сделал правильно. Это также заставляет assert библиотеку создавать совершенно новый подъязык вместо использования существующего языка программирования (самого Go)._ https://go.dev/wiki/TestComments

2024-07-15 19:50 UTC, vokinneberg commented on internal/handlers/handlers_test.go
> +			assert.Equal(t, tt.want.statusCode, result.StatusCode)
Было бы здорово добавить дополнительные информативные сообщения у ассертам о том, что ожидалось и что пошло не так.

2024-07-15 19:50 UTC, vokinneberg commented on internal/handlers/handlers.go
> +var urlStore = make(map[string]string)
Предлагаю на будущее подумать о том, как будет работать MemStore в условиях многочисленных одновременных запросов, причем когда на чтение запросов приходит кратно больше? Стоит добавить синхронизацию?

2024-07-16 20:45 UTC, romanp1989 commented on cmd/shortener/main.go
> +		panic(err)
Исправил

2024-07-16 20:52 UTC, romanp1989 commented on cmd/client/main.go
> +func main() {
Этот клиент скопирован как есть из кода курса. В уроке была рекомендация скопировать этот код к себе в проект для дальнейшего использования.

2024-07-16 20:57 UTC, romanp1989 commented on cmd/client/main.go
> +		panic(err)
Исправил

2024-07-16 20:57 UTC, romanp1989 commented on internal/handlers/handlers.go
> +	if r.Method != http.MethodPost {
Убрал проверку

2024-07-16 20:57 UTC, romanp1989 commented on internal/handlers/handlers.go
> +	}
Добавил defer

2024-07-16 20:57 UTC, romanp1989 commented on internal/handlers/handlers.go
> +	http.Error(w, "Не найден url для указанного ID", http.StatusBadRequest)
Исправил

2024-07-16 20:58 UTC, romanp1989 commented on internal/handlers/handlers_test.go
> +			name:        "Valid URL",
Добавил underscore в качестве разделителя в название тестов.

2024-07-16 21:08 UTC, romanp1989 commented on cmd/client/main.go
> +func main() {
Разделил код клиента на блоки

2024-07-16 21:08 UTC, romanp1989 commented on cmd/client/main.go
> +	endpoint := "http://localhost:8080/"
Вынес значение в константу

2024-07-16 21:28 UTC, romanp1989 commented on internal/config/config.go
> +		log.Fatal(err)
Исправил логирование ошибки при парсинге флагов. Добавил в качестве возвращаемого значения структуру со значения флагов и переменных окружения.

2024-07-18 09:31 UTC, romanp1989 commented on internal/handlers/handlers_test.go
> +			assert.Equal(t, tt.want.statusCode, result.StatusCode)
Добавил сообщения при ошибках в тестах

2024-07-18 09:36 UTC, romanp1989 commented on internal/handlers/handlers_test.go
> +			assert.Equal(t, tt.want.responseURL, string(resBody))
Согласен, что лучше использовать родную библиотеку Go test. Но в примерах урока применяется testify, поэтому делал тесты по аналогии.

2024-07-19 22:53 UTC, vokinneberg commented on cmd/client/main.go
> +func main() {
Спасибо 🙏 ! Не смотря на то, что этот код скопирован из кода курса на мой взгляд его все равно можно улучшить, особенно учитывая, что я стараюсь проводить ревью по стандартам продакшн кода 🤓

2024-07-19 22:58 UTC, vokinneberg approved these changes
Привет! 👋 Вижу, что ты  учел моим комментарии.👍  Вижу, что в одном месте ты не заметил использованный `panic()` - разберемся с этим в следующем спринте. Поздравляю с завершением первого спринта и завершением первого ревью! 🤗 Отличная работа! 🚀

2024-07-19 22:58 UTC, vokinneberg commented on cmd/client/main.go
> +		panic(err)
Не заметил `panic()` тут.

2024-07-21 09:52 UTC, merged